// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-ZS6HrcVdvpeiIBaYVqMxcZP8Hy28-AU',
    appId: '1:1080783324237:android:c2f7ae8061c3f632ee4804',
    messagingSenderId: '1080783324237',
    projectId: 'finshyt-649a8',
    storageBucket: 'finshyt-649a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBeRb32V6WufpQyV2FFtbT6DQbXBCCTcA',
    appId: '1:1080783324237:ios:3e6b20c4e4378170ee4804',
    messagingSenderId: '1080783324237',
    projectId: 'finshyt-649a8',
    storageBucket: 'finshyt-649a8.firebasestorage.app',
    iosBundleId: 'com.example.finshyt',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAYoIi64lDZ3TGIR4lmdKQ2lwLIVc5DIc',
    appId: '1:1080783324237:web:43368b424f4b687cee4804',
    messagingSenderId: '1080783324237',
    projectId: 'finshyt-649a8',
    authDomain: 'finshyt-649a8.firebaseapp.com',
    storageBucket: 'finshyt-649a8.firebasestorage.app',
    measurementId: 'G-5Y5LQ84REV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBeRb32V6WufpQyV2FFtbT6DQbXBCCTcA',
    appId: '1:1080783324237:ios:3e6b20c4e4378170ee4804',
    messagingSenderId: '1080783324237',
    projectId: 'finshyt-649a8',
    storageBucket: 'finshyt-649a8.firebasestorage.app',
    iosBundleId: 'com.example.finshyt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAYoIi64lDZ3TGIR4lmdKQ2lwLIVc5DIc',
    appId: '1:1080783324237:web:ec5b7256c9967b26ee4804',
    messagingSenderId: '1080783324237',
    projectId: 'finshyt-649a8',
    authDomain: 'finshyt-649a8.firebaseapp.com',
    storageBucket: 'finshyt-649a8.firebasestorage.app',
    measurementId: 'G-BJFJX8XRMX',
  );

}